### ISSUE TITLE
Image Pull and run fails 

### ISSUE THREAD

**Issue by Jsyro** [decentralized-identity/uni-resolver-driver-did-sov#4]
When running docker-compose up on this file.
```
version: "3.5"
networks:
  default:
    name: universal-resolver
services:
  driver-did-sov:
    image: universalresolver/driver-did-sov
    environment:
      uniresolver_driver_did_sov_libIndyPath:
      uniresolver_driver_did_sov_poolConfigs: "_;./local/localhost_9000.txn"
      uniresolver_driver_did_sov_poolVersions: _;2;
      uniresolver_driver_did_sov_walletName: wallet
    ports:
      - "7776:8080"
    volumes:
      - ./:/opt/driver-did-sov/local
```
The containers errors on startup with the following error. 
```
Attaching to resolver_driver-did-sov_1
driver-did-sov_1  | WARNING: An illegal reflective access operation has occurred
driver-did-sov_1  | WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
driver-did-sov_1  | WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
driver-did-sov_1  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
driver-did-sov_1  | WARNING: All illegal access operations will be denied in a future release
driver-did-sov_1  | [INFO] Scanning for projects...
driver-did-sov_1  | Downloading from sovrin: https://repo.sovrin.org/repository/maven-public/decentralized-identity/uni-resolver/0.3-SNAPSHOT/maven-metadata.xml
driver-did-sov_1  | Downloading from danubetech-maven-public: https://repo.danubetech.com/repository/maven-public/decentralized-identity/uni-resolver/0.3-SNAPSHOT/maven-metadata.xml
Downloaded from danubetech-maven-public: https://repo.danubetech.com/repository/maven-public/decentralized-identity/uni-resolver/0.3-SNAPSHOT/maven-metadata.xml (611 B at 641 B/s)
driver-did-sov_1  | Downloading from danubetech-maven-public: https://repo.danubetech.com/repository/maven-public/decentralized-identity/uni-resolver/0.3-SNAPSHOT/uni-resolver-0.3-20210423.161953-110.pom
Downloaded from danubetech-maven-public: https://repo.danubetech.com/repository/maven-public/decentralized-identity/uni-resolver/0.3-SNAPSHOT/uni-resolver-0.3-20210423.161953-110.pom (11 kB at 23 kB/s)
driver-did-sov_1  | [ERROR] [ERROR] Some problems were encountered while processing the POMs:
driver-did-sov_1  | [ERROR] 'dependencies.dependency.version' for io.leonard:base58:jar must be a valid version but is '${io.leonard-base58.version}'. @ line 134, column 13
driver-did-sov_1  |  @ 
driver-did-sov_1  | [ERROR] The build could not read 1 project -> [Help 1]
driver-did-sov_1  | [ERROR]   
driver-did-sov_1  | [ERROR]   The project decentralized-identity:uni-resolver-driver-did-sov:0.3-SNAPSHOT (/opt/driver-did-sov/pom.xml) has 1 error
driver-did-sov_1  | [ERROR]     'dependencies.dependency.version' for io.leonard:base58:jar must be a valid version but is '${io.leonard-base58.version}'. @ line 134, column 13
driver-did-sov_1  | [ERROR] 
driver-did-sov_1  | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
driver-did-sov_1  | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
driver-did-sov_1  | [ERROR] 
driver-did-sov_1  | [ERROR] For more information about the errors and possible solutions, please read the following articles:
driver-did-sov_1  | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```
